### ISSUE TITLE
start a new file swaytse.tex in tse format

### ISSUE THREAD

**Issue by timm** [Ginfung/Reports#15]
please recall that , sooner or later,   

- [ ] your  the quartile charts have to be in the format of https://github.com/ai-se/Paper_Sampling_vs_EA/blob/master/quartiles.tex
- [ ] apart from HV and spread, we need quartiles and scott knot for 2 more: runtimes and evals/

also, you will need a tex document ...

- [ ] of the format http://get-software.net/macros/latex/contrib/IEEEtran/bare_jrnl.tex 

for more details on that format, see http://get-software.net/macros/latex/contrib/IEEEtran)

**Comment by Ginfung** [comment]
Need to finalize the graphs first and then transfer them into latex format.

**Comment by Ginfung** [comment]
@timm would you create a sharelatex project by your account?

**Comment by timm** [comment]
did u get the invite? if ues, plz close this issue
