### ISSUE TITLE
group# (granuity) vs. quality

### ISSUE THREAD

**Issue by Ginfung** [Ginfung/Reports#22]
report the median for 10 repeats

webportal

| #group | hypervolume | spread |
|--------|-------------|--------|
| 2      | 0.335       | 0.613  |
| 4      | 0.328       | 0.603  |
| 5      | 0.333       | 0.612  |
| 10     | 0.332       | 0.634  |
| 20     | 0.329       | 0.625  |

eshop

| #group | hypervolume | spread |
|--------|-------------|--------|
| 2      | 0.265       | 0.717  |
| 8      | 0.265       | 0.687  |
| 32     | 0.263       | 0.669  |
| 64     | 0.262       | 0.687  |
| 128    | 0.265       | 0.699  |

higher #group means higher #evaluations

**Comment by Ginfung** [comment]
@timm it seems the granularity has nothing to do with precision in small models.  :(
ignore this in the paper?!

**Comment by timm** [comment]
that is strange. is this with the new cdom ? or the old one?

**Comment by Ginfung** [comment]
@timm only one cdom version in my code, and I've checked that through Fonseca function.

**Comment by Ginfung** [comment]
@timm we expect that hv/spread can be improved by setting the granularity smaller. But the experiments rejected this.

**Comment by timm** [comment]
these are medians, right? you got ALL the spreads and hypervolumes? 

- for eshop group=2,  sort and chart them
- for eshop group=128, sort and chart on the same chart as group=2

what is group?

**Comment by Ginfung** [comment]
@timm granularity=#decs/#group

**Comment by timm** [comment]
?

**Comment by Ginfung** [comment]
group is the measure of granularity.
The larger group,
smaller granularity and larger number of evaluations.

**Comment by timm** [comment]
?

**Comment by timm** [comment]
can u show it too me in an algorithm?

is it like the stopping crteria when you grow the trees? or?

**Comment by Ginfung** [comment]
![screen shot 2016-08-03 at 7 51 02 pm](https://cloud.githubusercontent.com/assets/3222148/17385889/a757e0b2-59b3-11e6-82be-57966291b86b.png)
![screen shot 2016-08-03 at 7 51 10 pm](https://cloud.githubusercontent.com/assets/3222148/17385892/a8fd8f2a-59b3-11e6-9215-28c06f96292a.png)

**Comment by Ginfung** [comment]
in a short, to solve the software product line problem by sway, the candidates should be grouped. Poles are compared inside the groups (no inter-group comparisons)

**Comment by Ginfung** [comment]
so if group=1, we're back to previous sway version.

increasing the groups->smaller granuity and more #evaluations

**Comment by timm** [comment]
the fog is beginning to clear.

will need to talk to you more about this but i see where ur going
