### ISSUE TITLE
Week Oct 18

### ISSUE THREAD

**Issue by Ginfung** [Ginfung/Reports#27]
# DOING
- plan to write the LACE2 application paper
- working on the SSBSE paper [stage1](https://github.com/ai-se/Paper_Sampling_vs_EA/milestone/1)
# DONE
- a paper review [repo](https://github.com/Ginfung/PaperReviews). plan to add 2-3 papers into the repo every week
# TODO
- SSBSE paper extension
- Section 1 of the LACE2 application
# ROADBLOCKS

I want to use the SWAY into QoS optimization. However, in cast studies of http://www.prismmodelchecker.org/ , it's difficult to define the conflict objectives.

Inspired by http://link.springer.com/chapter/10.1007/978-3-319-24499-0_14 I want to follow its instruction to define the qos objectives. Also I am very interested in the software architectures. 
Now the difficulty is how to find the benchmarks, from the open source software or other open data portal.
# ADMIN

@timm would you create a sharelatex project for the lace2 application paper? I don't have an upgraded account.

**Comment by timm** [comment]
created: 

lace2superprivate in sharelatex    
ai-se/lace2superprivate (private) in github

**Comment by Ginfung** [comment]
@timm saw that. thank you.
